import os
from flask import Flask, send_from_directory

# Initialize Flask app
# We tell Flask that static files are located in the 'dist' folder generated by Vite
app = Flask(__name__, static_folder='dist')

@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def serve(path):
    """
    Serve static files from the 'dist' directory.
    If the file doesn't exist (e.g., a React route like /profile),
    serve index.html so React Router can handle it on the client side.
    """
    if path != "" and os.path.exists(app.static_folder + '/' + path):
        return send_from_directory(app.static_folder, path)
    
    return send_from_directory(app.static_folder, 'index.html')

if __name__ == '__main__':
    # Run the app
    # Host '0.0.0.0' allows external access (required for deployment)
    app.run(host='0.0.0.0', port=int(os.environ.get("PORT", 5000)))
